#!/usr/bin/env python

import os, sys
from StringIO import StringIO
from testify import *

expect(1)

os.chdir(os.path.dirname(__file__))
sys.argv = [sys.argv[0], 'data/decoratedExpect']

save = sys.stdout
sys.stdout = StringIO()

execfile('../testify', {})

stdout = sys.stdout
sys.stdout = save

equal('''1..1
ok 1
1..1
not ok 1 "Not" "Equal"
1..1
FAIL 1 0
''', stdout.getvalue())
