#!/usr/bin/env python

import os, re, sys
from StringIO import StringIO
from testify import *

traceback = '''(?:  File ".+", line \d+, in .+
    .+
)+'''

os.chdir(os.path.dirname(__file__))
sys.argv = sys.argv[0], 'data/decoratedExpect'

stdout = sys.stdout
sys.stdout = StringIO()

try:
  execfile('../testify', {})

finally:
  stdout, sys.stdout = sys.stdout, stdout

ok(re.match('''# data/decoratedExpect
# expectPass
1..1
ok 1
# expectFail
1..1
not ok 1
# 'Actual'
# 'Expect'
''' + traceback + '''# notExpect
1..1
FAIL 1 0
''', stdout.getvalue()), stdout.getvalue())
