#!/usr/bin/env python

import os, sys
from StringIO import StringIO
from testify import *

expect(1)

os.chdir(os.path.dirname(__file__))
sys.argv = [sys.argv[0], 'data/decorated']

stdout = StringIO()
sys.stdout = stdout

execfile('../testify', {})

sys.stdout = sys.__stdout__

equal('''PASS
FAIL "Not" "Equal"
''', stdout.getvalue())
