#!/usr/bin/env python

import re, sys
from StringIO import StringIO
from testify import *

traceback = '''(?:  File ".+", line \d+, in .+
    .+
)+'''

stdout = sys.stdout
sys.stdout = StringIO()

try:
  test(lambda: equal('Equal', 'Equal'))

finally:
  stdout, sys.stdout = sys.stdout, stdout

equal('''# <lambda>
ok 1
''', stdout.getvalue())

stdout = sys.stdout
sys.stdout = StringIO()

try:
  test(lambda: equal('Expect', 'Actual'))

finally:
  stdout, sys.stdout = sys.stdout, stdout

ok(re.match('''# <lambda>
not ok 1
# 'Actual'
# 'Expect'
''' + traceback, stdout.getvalue()), stdout.getvalue())
