#!/usr/bin/env python

import os, re, sys
from StringIO import StringIO
from testify import *

traceback = '''(?:  File ".+", line \d+, in .+
    .+
)+'''

os.chdir(os.path.dirname(__file__))

sys.argv = [sys.argv[0], 'data/expectPass']

save = sys.stdout
sys.stdout = StringIO()

execfile('../testify', {})

stdout = sys.stdout
sys.stdout = save

equal('''1..1
ok 1
''', stdout.getvalue())

sys.argv = [sys.argv[0], 'data/expectFail']

save = sys.stdout
sys.stdout = StringIO()

execfile('../testify', {})

stdout = sys.stdout
sys.stdout = save

ok(re.match('''1..1
not ok 1 'Not' 'Equal'
''' + traceback, stdout.getvalue()), stdout.getvalue())

sys.argv = [sys.argv[0], 'data/notExpect']

save = sys.stdout
sys.stdout = StringIO()

execfile('../testify', {})

stdout = sys.stdout
sys.stdout = save

ok(re.match('''1..1
FAIL 1 0
''' + traceback, stdout.getvalue()), stdout.getvalue())
