#!/usr/bin/env python

import os, sys
from StringIO import StringIO
from testify import equal, expect, ok, test

expect(3)

os.chdir(os.path.dirname(__file__))
sys.argv = [sys.argv[0], 'data/expectPass']

stdout = StringIO()
sys.stdout = stdout

execfile('../testify', {})

sys.stdout = sys.__stdout__

equal('''PASS
''', stdout.getvalue())

sys.argv = [sys.argv[0], 'data/expectFail']

stdout = StringIO()
sys.stdout = stdout

execfile('../testify', {})

sys.stdout = sys.__stdout__

equal('''FAIL "Not" "Equal"
''', stdout.getvalue())

sys.argv = [sys.argv[0], 'data/notExpect']

stdout = StringIO()
sys.stdout = stdout

execfile('../testify', {})

sys.stdout = sys.__stdout__

equal('''FAIL 1 0
''', stdout.getvalue())
