#!/usr/bin/env python

import os, sys
from StringIO import StringIO
from testify import *

os.chdir(os.path.dirname(__file__))

@test
def expectPass():
  expect(1)

  sys.argv = [sys.argv[0], 'data/expectPass']

  stdout = StringIO()
  sys.stdout = stdout

  execfile('../testify', {})

  sys.stdout = sys.__stdout__

  equal('''1..1
ok 1
''', stdout.getvalue())

@test
def expectFail():
  expect(1)

  sys.argv = [sys.argv[0], 'data/expectFail']

  stdout = StringIO()
  sys.stdout = stdout

  execfile('../testify', {})

  sys.stdout = sys.__stdout__

  equal('''1..1
not ok 1 "Not" "Equal"
''', stdout.getvalue())

@test
def notExpect():
  expect(1)

  sys.argv = [sys.argv[0], 'data/notExpect']

  stdout = StringIO()
  sys.stdout = stdout

  execfile('../testify', {})

  sys.stdout = sys.__stdout__

  equal('''1..1
FAIL 1 0
''', stdout.getvalue())
