#!/usr/bin/env python

import os, re, sys
from StringIO import StringIO
from testify import *

traceback = '''(?:  File ".+", line \d+, in .+
    .+
)+'''

os.chdir(os.path.dirname(__file__))
sys.argv = [sys.argv[0], 'data/script', 'data/script']

stdout = sys.stdout
sys.stdout = StringIO()

execfile('../testify', {})

stdout, sys.stdout = sys.stdout, stdout

ok(re.match('''ok 1
not ok 2 'Not' 'Equal'
''' + traceback + '''ok 1
not ok 2 'Not' 'Equal'
''' + traceback, stdout.getvalue()), stdout.getvalue())
