#!/usr/bin/env python

import re, sys
from StringIO import StringIO
from testify import *

traceback = '''(?:  File ".+", line \d+, in .+
    .+
)+'''

stdout = sys.stdout
sys.stdout = StringIO()

try:
  test(lambda: ok(True))

finally:
  stdout, sys.stdout = sys.stdout, stdout

equal('''ok 1
''', stdout.getvalue())

stdout = sys.stdout
sys.stdout = StringIO()

try:
  test(lambda: ok(False))

finally:
  stdout, sys.stdout = sys.stdout, stdout

ok(re.match('''not ok 1
''' + traceback, stdout.getvalue()), stdout.getvalue())
