#!/usr/bin/env python

import sys
from StringIO import StringIO
from testify import *

@test
def okTrue():
  expect(1)

  save = sys.stdout
  sys.stdout = StringIO()

  test(lambda: ok(True))

  stdout = sys.stdout
  sys.stdout = save

  equal('''ok 1
''', stdout.getvalue())

@test
def okFalse():
  expect(1)

  save = sys.stdout
  sys.stdout = StringIO()

  test(lambda: ok(False))

  stdout = sys.stdout
  sys.stdout = save

  equal('''not ok 1
''', stdout.getvalue())
