#!/usr/bin/env python

import os, sys
from StringIO import StringIO
from testify import *

expect(1)

os.chdir(os.path.dirname(__file__))
sys.argv = [sys.argv[0], 'data/script']

save = sys.stdout
sys.stdout = StringIO()

execfile('../testify', {})

stdout = sys.stdout
sys.stdout = save

equal('''ok 1
not ok 2 "Not" "Equal"
''', stdout.getvalue())
