#!/usr/bin/env python

from testify import *

@test
def expectPass():
  expect(1)

  equal('Equal', 'Equal')

@test
def expectFail():
  expect(1)

  equal('Equal', 'Not')

@test
def notExpect():
  expect(1)
